# Autogenerated by devscripts/update-version.py

__version__ = '2026.08.04.234419'

RELEASE_GIT_HEAD = '5d6b8c8cd19785c3086ae3a9ec618c45e25eb3bc'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'yt-dlp/yt-dlp'

_pkg_version = '2026.08.04.234419dev'
